runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /$
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*)
  static_files: dist/\1
  upload: (.*)
  secure: always

skip_files:
  - ^(.*/)?
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - gulpfile.js
  - test*
  - bower_components/[^/]+/bower_components/.*$
  - bower_components/(.+/)+(test/|demo/|README|AUTHORS|CONTRIBUTING|PATENTS|Makefile)
  - node_modules*
  - bower.json
